server:
  port: 8080
  tomcat:
    threads:
      max: 250

config:
  threadPoolSize: 250
  useFixedThreadPool: false
  flushMultipleRanges: false
  memTableHardLimit: 2000000
  memTableSoftLimit: 50000
